# .readthedocs.yaml
# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

build:
  tools:
    python: "3.10"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/conf.py
